sonar.projectKey=frontoffice-trustedwork
sonar.projectName=frontoffice-trustedwork
sonar.host.url=http://localhost:9000
sonar.token=sqp_4a70e8c6ea5f2755239c61b2fd42f359b2eeeb2b
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/environments/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info