package tn.esprit.userservice.entity;

public enum AuditEventType {
    LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT, TOKEN_REFRESHED,
    REGISTER, PASSWORD_CHANGED, PASSWORD_RESET_REQUESTED, PASSWORD_RESET_COMPLETED,
    ACCOUNT_LOCKED, ACCOUNT_UNLOCKED,
    KYC_SUBMITTED, KYC_APPROVED, KYC_REJECTED,
    TWO_FACTOR_ENABLED, TWO_FACTOR_DISABLED, TWO_FACTOR_VERIFIED,
    USER_SUSPENDED, USER_ACTIVATED, USER_DELETED, USER_CREATED_BY_ADMIN,
    TRUST_LEVEL_UPDATED
}